name: Build and deploy dotnet core project to Azure Function App - order-processor-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './OrderProcessor.Function'
  DOTNET_VERSION: '8.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Publish
        run: |
          pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd
      
      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'order-processor-func'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB882A935578408484E1FF2C41E2CB0C }}
