name: Build and deploy dotnet core project to Azure Function App - order-processor-func

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build and Publish
        run: |
          dotnet restore OrderProcessor.Function.csproj
          dotnet build OrderProcessor.Function.csproj --configuration Release
          dotnet publish OrderProcessor.Function.csproj --configuration Release --output ./output
      
      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'order-processor-func'
          package: './output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AB882A935578408484E1FF2C41E2CB0C }}
